#create database bombero;
/*use bombero;
create table serv_year(idserv_year int primary key auto_increment,
year int,
cant int,
total int);
create table mes(idmes int primary key auto_increment,
nombre varchar(45));
create table tabla(idtabla int primary key auto_increment,
tras_pac int,
cobertura int,
acc_trans int,
ani_ali int,
rescate int,
total_mes int,
inc_est int,
inc_past int,
inc_veh int);
create table mes_has_tabla(idmes int,
idtabla int,
foreign key(idmes) references mes(idmes),
foreign key(idtabla) references tabla(idtabla));
create table tipo_combus(idtipo_combus int primary key auto_increment,
descripcion varchar(45));
create table vehiculo(idvehiculo int primary key auto_increment,
descripcion varchar(45),
chapa varchar(45),
idtipo_combus int,
foreign key(idtipo_combus) references tipo_combus(idtipo_combus));
create table plan_combus(idplan_combus int primary key auto_increment,
periodo varchar(45),
idvehiculo int,
foreign key(idvehiculo) references vehiculo(idvehiculo),
fecha varchar(45),
ci varchar(45),
nombre varchar(45),
lugar_sal varchar(45),
km_salida int,
lugar_dest varchar(45),
km_llegada int,
km_recorrido int,
motivo varchar(45),
lts_carg int,
nro_fact varchar(45),
imp_total int);*/
/*create table diez40(id1040 int primary key auto_increment,
cant_global int,
hora_serv int);
create table serv_1040(idserv int primary key auto_increment,
estructural int,
vehicular int,
basural int,
forestal int,
pastizal int,
id1040 int,
foreign key(id1040) references diez40(id1040));
create table causa_posible(idcausa int primary key auto_increment,
desconocida int,
premeditada int,
accidental int,
corto_circuito int,
fineslimpieza int,
id1040 int,
foreign key(id1040) references diez40(id1040));
create table mag_1040(idmag int primary key auto_increment,
principio int,
pequenha int,
mediana int,
grande int,
emergencia_gral int,
id1040 int,
foreign key(id1040) references diez40(id1040));
create table movil(idmovil int primary key auto_increment,
nom_movil varchar(45),
km int);
create table diez41(id1041 int primary key auto_increment,
cant_global int,
hora_serv int);
create table serv_1041(idserv int primary key auto_increment,
arrollamiento int,
choque int,
vuelco int,
caida int,
aeronave int,
id1041 int,
foreign key(id1041)references diez41(id1041));
create table mag_1041(idmag int primary key auto_increment,
danho_mat varchar(45),
herido varchar(45),
atrapado varchar(45),
incendio varchar(45),
mat_pel varchar(45),
id1041 int,
foreign key(id1041)references diez41(id1041));
create table elem_inv(idelem int primary key auto_increment,
peaton varchar(45),
moto varchar(45),
veh_liviano varchar(45),
veh_pesado varchar(45),
bus varchar(45),
id1041 int,
foreign key(id1041)references diez41(id1041));
create table seg_inv(idseg int primary key auto_increment,
cint_conductor varchar(45),
cint_acomp varchar(45),
cas_conductor varchar(45),
cas_acomp varchar(45),
id1041 int,
foreign key(id1041)references diez41(id1041));
create table rec_util(idrec int primary key auto_increment,
agua int,
pqs_co2 int,
combuestible int,
bombero int,
kmrecorrido int,
tiempototal int,
nom_movil varchar(45),
id1040 int,
id1041 int,
foreign key(id1040)references diez40(id1040),
foreign key(id1041)references diez41(id1041));
create table diez43(id1043 int primary key auto_increment,
cant_global int,
hora_serv int);
create table serv_1043(id1043 int primary key auto_increment,
rescate int,
recuperacion int,
ani_ali int,
cobertura int,
curso_charla int,
transporte int,
id1043 int,
foreign key(id1043)references diez43(id1043));
create table rescate(idrescate int primary key auto_increment,
vivienda int,
profundidad int,
altura int,
derrumbe int,
raudal_nauf int,
amenaza_bomba int,
int_suic int,
id1043 int,
foreign key(id1043)references diez43(id1043));
create table cant_4445(idcant int primary key auto_increment,
ileso int,
herido int,
fallecido int,
rescate int,
id1040 int,
id1041 int,
id1043 int,
foreign key(id1040)references diez40(id1040),
foreign key(id1041)references diez41(id1041),
foreign key(id1043)references diez43(id1043));
create table ims(idims int primary key auto_increment,
fecha_env varchar(45),
hora_mes_anho varchar(45),
cant_cia_est int,
autor varchar(45),
telef varchar(45),
lugar_env varchar(45),
fax_hab varchar(45),
fecha_cierre_inf varchar(45),
cant_serv int,
id1040 int,
id1041 int,
id1043 int,
foreign key(id1040)references diez40(id1040),
foreign key(id1041)references diez41(id1041),
foreign key(id1043)references diez43(id1043));*/

